# docker-compose.yml
version: '3.8'

services:
  # Serviço da Aplicação Flask/Gunicorn
  cap_price__app:
    build: .
    container_name: cap_price_app
    volumes:
      - .:/app
    ports:
      - "5050:5000"
    env_file:
      - .env # Carrega variáveis de ambiente (ex: chaves de API)
